Blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'Blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<str:category>', views.post_list, name='post_list_category'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path('ticket/', views.ticket, name='ticket'),
    path('posts/<int:pk>/comments/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
    path('profile/', views.profile, name='profile'),
    path('profile/create_post/', views.create_post, name='create_post'),
    path('profile/create_post/<int:pk>', views.edit_post, name='edit_post'),
    path('profile/delete_post/<int:pk>', views.delete_post, name='delete_post'),
    path('profile/delete_image/<int:pk>', views.delete_image, name='delete_image'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='done'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password_reset/complete/'), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('account/edit', views.edit_account, name='edit_account'),
    path('profile/detail/<int:user_id>', views.profile_detail, name='profile_detail'),
]

sabzweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from Blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('Blog.urls', namespace='blog')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/forms.py
from django import forms
from Blog.models import Comment, Post, User, Account


class TicketForm(forms.Form):
    SUBJECT_CHOICES = [
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    ]

    name = forms.CharField(max_length=250, required=True, label="", widget=forms.TextInput(attrs={
        'placeholder': "نام و نام خانوادگی",
        'class': 'ticket-form-name  form-field',
    }))
    message = forms.CharField(required=True, label='', widget=forms.Textarea(attrs={
        "placeholder": 'متن پیام',
        'class': 'form-message form-field',
    }))
    email = forms.EmailField(label="", widget=forms.EmailInput(attrs={
        'placeholder': 'ایمیل',
        'class': 'ticket-form-email form-field',
    }))
    phone = forms.CharField(required=True, max_length=11, label="", widget=forms.TelInput(attrs={
        'placeholder': 'تلفن همراه',
        'class': 'ticket-form-phone form-field',
    }))
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label="موضوع")

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isdigit() and len(phone) != 11 and not phone[0:1] == '09':
                raise forms.ValidationError("شماره تلفن درست نیست!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body',)
        widgets = {
            'body': forms.Textarea(attrs={
                'class': 'form-message form-field',
                'placeholder': 'متن نظر'
            }),
            'name': forms.TextInput(attrs={
                'class': 'comment-form-name form-field',
                'placeholder': 'نام و نام خانوادگی'
            })
        }
        labels = {
            'name': "",
            'body': ''
        }


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", )
    image2 = forms.ImageField(label="تصویر دوم", )

    class Meta:
        model = Post
        fields = ('title', 'description', 'reading_time', 'category')
        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'عنوان',
                'class': 'form-field post-form--title'
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'متن پست',
                'class': 'form-field form-message'
            }),
            'reading_time': forms.TextInput(attrs={
                'placeholder': 'زمان مطالعه',
                'class': 'form-field post-form--reading-time'
            }),
            'category': forms.TextInput(attrs={
                'placeholder': 'دسته بندی',
            }),
        }
        labels = {
            'title': '',
            'description': '',
            'reading_time': '',
            'category': '',
        }


class SearchForm(forms.Form):
    query = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={
        'placeholder': 'جستجو',
        'class': ''
    }))


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, required=True, label='', widget=forms.PasswordInput(attrs={}))
    password2 = forms.CharField(max_length=20, required=True, label='', widget=forms.PasswordInput(attrs={}))

    class Meta:
        model = User
        fields = ('username', "first_name", "last_name", 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("رمز ها مطابقت ندارند")
        else:
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('date_of_birth', 'bio', 'job', 'photo')

Blog/views.py
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
# from django.contrib.auth import authenticate, login, logout
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
# from django.views.generic import ListView
# from django.http import HttpResponse
from django.db.models import Q
from .models import *
from .forms import *


# Create your views here.

def index(request):
    return render(request, 'blog/index.html')


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category,
    }
    return render(request, 'blog/list.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active=True)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(
                message=cd['message'],
                name=cd['name'],
                email=cd['email'],
                phone=cd['phone'],
                subject=cd['subject']
            )
            return redirect('blog:post_list')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, 'forms/comment.html', context)


@login_required()
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(post=post, image_file=request.FILES['image1'])
            Image.objects.create(post=post, image_file=request.FILES['image2'])
            return redirect('blog:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create_post.html', {'form': form})


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = (Post.published.annotate(
                sim_post_title=TrigramSimilarity('title', query),
                sim_post_desc=TrigramSimilarity('description', query),
                sim_image_title=TrigramSimilarity("images__title", query),
                sim_image_desc=TrigramSimilarity("images__description", query)).filter(
                Q(sim_post_title__gt=0.1) |
                Q(sim_post_desc__gt=0) |
                Q(sim_image_title__gt=0.1) |
                Q(sim_image_desc__gt=0)
            ))

    context = {
        'query': query,
        'results': results
    }
    return render(request, 'blog/search.html', context)


@login_required()
def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)
    return render(request, 'blog/profile.html', {'posts': posts})


@login_required()
def delete_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    else:
        return render(request, 'forms/delete_post.html', {'post': post})


@login_required()
def delete_image(request, pk):
    image = get_object_or_404(Image, id=pk)
    image.delete()
    return redirect('blog:profile')


@login_required()
def edit_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(post=post, image_file=request.FILES['image1'])
            Image.objects.create(post=post, image_file=request.FILES['image2'])
            return redirect('blog:profile')
    else:
        form = CreatePostForm(instance=post)
    context = {
        'post': post,
        'form': form
    }
    return render(request, 'forms/create_post.html', context)


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required()
def edit_account(request):
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, request.FILES, instance=request.user.account)
        if user_form.is_valid() and account_form.is_valid():
            user_form.save()
            account_form.save()
            return redirect("blog:profile")
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {
        'user_form': user_form,
        'account_form': account_form
    }
    return render(request, 'registration/edit_account.html', context)


def profile_detail(request, user_id):
    user = get_object_or_404(User, id=user_id)
    account = user.account
    posts = Post.published.filter(author=user)
    context = {
        'user': user,
        'account': account,
        'posts': posts
    }
    return render(request, 'blog/profile_detail.html', context)

Blog/templates/partials/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'CSS/partials/footer.css' %}">

<footer>
    <div class="footer-container">
        <div class="footer-col">
            <h3>درباره ما</h3>
            <p>
                ما در این وبلاگ تلاش می‌کنیم جدیدترین مطالب دنیای تکنولوژی، بلاک‌چین و نوآوری را با شما به اشتراک بگذاریم.
            </p>
        </div>

        <div class="footer-col">
            <h3>دسترسی سریع</h3>
            <a href="{% url 'blog:index' %}">خانه</a>
            <a href="{% url 'blog:post_list' %}">پست‌ها</a>
            <a href="#">دسته‌بندی‌ها</a>
            <a href="#">تماس با ما</a>
        </div>

        <div class="footer-col">
            <h3>ما را دنبال کنید</h3>
            <div class="footer-social">
                <!-- Instagram -->
                <a href="https://www.instagram.com/sh_mr.mhmd?igsh=bWFxbXNza3BxcmNp" title="Instagram" aria-label="Instagram">
                    <img src="{% static 'icons/Instagram.svg' %}" alt="">
                </a>
        
                <!-- Telegram -->
                <a href="https://t.me/MR0MHMD" title="Telegram"  aria-label="Telegram">
                    <img src="{% static 'icons/Telegram.svg' %}" alt="">
                </a>
        
                <!-- GitHub -->
                <a href="https://github.com/MR0MHMD" title="GitHub" aria-label="GitHub">
                    <img src="{% static 'icons/GitHub.svg' %}" alt="">
                </a>
            </div>
        </div>

        <div class="footer-col">
            <h3>خبرنامه</h3>
            <p>برای دریافت آخرین پست‌ها ایمیل خود را وارد کنید:</p>
            <form>
                <input type="email" placeholder="ایمیل شما..." required>
                <input type="submit" value="عضویت">
            </form>
        </div>
    </div>

    <div class="footer-bottom">
        © 2025 MyBlog — تمامی حقوق محفوظ است.
    </div>
</footer>

Blog/templates/partials/header.html
{% load static %}

<link rel="stylesheet" href="{% static "CSS/partials/header.css" %}">

<header>
    <nav class="navbar">
        <!-- Logo -->
        <div class="logo">MyBlog</div>

        <!-- Navigation Links -->
        <div class="nav-links">
            <a href="{% url 'blog:index' %}">خانه</a>
            <a href="#">دسته‌بندی‌ها</a>
            <a href="#">درباره ما</a>
            <a href="{% url 'blog:ticket' %}">تماس با ما</a>
        </div>

        <!-- Search Box -->
        <form class="search-box" method="get" action="{% url 'blog:post_search' %}">
            <input type="text" name="query" placeholder="جست‌وجو...">
            <button type="submit" class="search-btn">🔍</button>
        </form>

        <!-- Profile / Auth -->
        {% if request.user.is_authenticated %}
            <div class="user-actions">
                <a href="{% url 'blog:profile' %}" class="signup">{{ user.username }}</a>
            </div>
        {% else %}
            <div class="user-actions">
                <a href="{% url 'blog:login' %}" class="signup">ورود</a>
            </div>
        {% endif %}
    </nav>
</header>

Blog/templates/partials/latest_posts.html
{% load jformat %}
{% load blog_tags %}
<div>
    {% for post in l_posts %}
        <div class="posts-cont">
            <div class="post-image--cont">
                <img class="post-image" src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
            </div>
            <div class="post-data">
                <div class="profile-info--cont">
                    <img class="profile-image" src="{{ post.author.account.photo.url }}" alt="">
                    <a class="username-link" href="{% url 'blog:profile_detail' post.author.id %}">{{ post.author }}</a>
                </div>
                <div class="post-info">
                    <h3><a class="title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                    <div class="post-desc">{{ post.description | markdown | truncatewords:25 }}</div>
                    <p class="post-time">{{ post.publish | jformat:'%Y/%m/%d | %H:%M ' }}</p>
                </div>

            </div>
        </div>
    {% endfor %}
</div>

Blog/templates/partials/navigation.html
{#<p>Navigation</p>#}

Blog/templates/partials/pagination.html
{% load static %}

    <style>
        .pagination {
            display: flex;
            justify-content: center;
            margin-top: 20px;
            gap: 8px;
            font-family: Arial, sans-serif;
        }

        .pagination a, .pagination span {
            padding: 8px 12px;
            border: 1px solid #ccc;
            border-radius: 5px;
            text-decoration: none;
            color: #333;
            transition: all 0.2s ease-in-out;
        }

        .pagination .active {
            background-color: #007bff;
            color: white;
            font-weight: bold;
            border-color: #007bff;
        }

        .pagination a:hover {
            background-color: #f0f0f0;
            border-color: #999;
        }

        .pagination .disabled {
            color: #aaa;
            background-color: #f0f0f0;
            border-color: #eee;
            pointer-events: none;
        }
    </style>
<body>

    <div class="pagination">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">&#171; قبلی</a>
        {% else %}
            <span class="disabled">&#171; قبلی</span>
        {% endif %}

        {% for num in posts.paginator.page_range %}
            {% if num >= posts.number|add:'-2' and num <= posts.number|add:'2' %}
                {% if posts.number == num %}
                    <span class="active">{{ num }}</span>
                {% else %}
                    <a href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endif %}
        {% endfor %}

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">بعدی &#187;</a>
        {% else %}
            <span class="disabled">بعدی &#187;</span>
        {% endif %}
    </div>