Blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'Blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<str:category>', views.post_list, name='post_list_category'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path('ticket/', views.ticket, name='ticket'),
    path('posts/<int:pk>/comments/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
    path('profile/', views.profile, name='profile'),
    path('profile/create_post/', views.create_post, name='create_post'),
    path('profile/create_post/<int:pk>', views.edit_post, name='edit_post'),
    path('profile/delete_post/<int:pk>', views.delete_post, name='delete_post'),
    path('profile/delete_image/<int:pk>', views.delete_image, name='delete_image'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url='done'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password_reset/complete/'), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('account/edit', views.edit_account, name='edit_account'),
    path('profile/detail/<int:user_id>', views.profile_detail, name='profile_detail'),
]

sabzweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from Blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('Blog.urls', namespace='blog')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/forms.py
from django import forms
from Blog.models import Comment, Post, User, Account


class TicketForm(forms.Form):
    SUBJECT_CHOICES = [
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    ]

    name = forms.CharField(max_length=250, required=True, label="", widget=forms.TextInput(attrs={
        'placeholder': "نام و نام خانوادگی",
        'class': 'ticket-form-name  form-field',
    }))
    message = forms.CharField(required=True, label='', widget=forms.Textarea(attrs={
        "placeholder": 'متن پیام',
        'class': 'form-message form-field',
    }))
    email = forms.EmailField(label="", widget=forms.EmailInput(attrs={
        'placeholder': 'ایمیل',
        'class': 'ticket-form-email form-field',
    }))
    phone = forms.CharField(required=True, max_length=11, label="", widget=forms.TelInput(attrs={
        'placeholder': 'تلفن همراه',
        'class': 'ticket-form-phone form-field',
    }))
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label="موضوع")

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isdigit() and len(phone) != 11 and not phone[0:1] == '09':
                raise forms.ValidationError("شماره تلفن درست نیست!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body',)
        widgets = {
            'body': forms.Textarea(attrs={
                'class': 'form-message form-field',
                'placeholder': 'متن نظر'
            }),
            'name': forms.TextInput(attrs={
                'class': 'comment-form-name form-field',
                'placeholder': 'نام و نام خانوادگی'
            })
        }
        labels = {
            'name': "",
            'body': ''
        }


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", )
    image2 = forms.ImageField(label="تصویر دوم", )

    class Meta:
        model = Post
        fields = ('title', 'description', 'reading_time', 'category')
        widgets = {
            'title': forms.TextInput(attrs={
                'placeholder': 'عنوان',
                'class': 'form-field post-form--title'
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'متن پست',
                'class': 'form-field form-message'
            }),
            'reading_time': forms.TextInput(attrs={
                'placeholder': 'زمان مطالعه',
                'class': 'form-field post-form--reading-time'
            }),
            'category': forms.TextInput(attrs={
                'placeholder': 'دسته بندی',
            }),
        }
        labels = {
            'title': '',
            'description': '',
            'reading_time': '',
            'category': '',
        }


class SearchForm(forms.Form):
    query = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={
        'placeholder': 'جستجو',
        'class': ''
    }))


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, required=True, label='', widget=forms.PasswordInput(attrs={}))
    password2 = forms.CharField(max_length=20, required=True, label='', widget=forms.PasswordInput(attrs={}))

    class Meta:
        model = User
        fields = ('username', "first_name", "last_name", 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("رمز ها مطابقت ندارند")
        else:
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('date_of_birth', 'bio', 'job', 'photo')

Blog/views.py
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
# from django.contrib.auth import authenticate, login, logout
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
# from django.views.generic import ListView
# from django.http import HttpResponse
from django.db.models import Q
from .models import *
from .forms import *


# Create your views here.

def index(request):
    return render(request, 'blog/index.html')


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category,
    }
    return render(request, 'blog/list.html', context)


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active=True)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(
                message=cd['message'],
                name=cd['name'],
                email=cd['email'],
                phone=cd['phone'],
                subject=cd['subject']
            )
            return redirect('blog:post_list')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


@require_POST
def post_comment(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment,
    }
    return render(request, 'forms/comment.html', context)


@login_required()
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(post=post, image_file=request.FILES['image1'])
            Image.objects.create(post=post, image_file=request.FILES['image2'])
            return redirect('blog:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create_post.html', {'form': form})


def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = (Post.published.annotate(
                sim_post_title=TrigramSimilarity('title', query),
                sim_post_desc=TrigramSimilarity('description', query),
                sim_image_title=TrigramSimilarity("images__title", query),
                sim_image_desc=TrigramSimilarity("images__description", query)).filter(
                Q(sim_post_title__gt=0.1) |
                Q(sim_post_desc__gt=0) |
                Q(sim_image_title__gt=0.1) |
                Q(sim_image_desc__gt=0)
            ))

    context = {
        'query': query,
        'results': results
    }
    return render(request, 'blog/search.html', context)


@login_required()
def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)
    return render(request, 'blog/profile.html', {'posts': posts})


@login_required()
def delete_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    else:
        return render(request, 'forms/delete_post.html', {'post': post})


@login_required()
def delete_image(request, pk):
    image = get_object_or_404(Image, id=pk)
    image.delete()
    return redirect('blog:profile')


@login_required()
def edit_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(post=post, image_file=request.FILES['image1'])
            Image.objects.create(post=post, image_file=request.FILES['image2'])
            return redirect('blog:profile')
    else:
        form = CreatePostForm(instance=post)
    context = {
        'post': post,
        'form': form
    }
    return render(request, 'forms/create_post.html', context)


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required()
def edit_account(request):
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, request.FILES, instance=request.user.account)
        if user_form.is_valid() and account_form.is_valid():
            user_form.save()
            account_form.save()
            return redirect("blog:profile")
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {
        'user_form': user_form,
        'account_form': account_form
    }
    return render(request, 'registration/edit_account.html', context)


def profile_detail(request, user_id):
    user = get_object_or_404(User, id=user_id)
    account = user.account
    posts = Post.published.filter(author=user)
    context = {
        'user': user,
        'account': account,
        'posts': posts
    }
    return render(request, 'blog/profile_detail.html', context)

Blog/templates/blog/detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load blog_tags %}
{% load jformat %}
{% block title %}
    post detail
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'CSS/blog/detail.css' %}">
{#    <link rel="stylesheet" href="{% static 'CSS/forms/forms.css' %}">#}
    
{% endblock %}
{% block content %}
     <main class="page" role="main">

        <section class="content-grid">

            <!-- Slider Section (keep structure) -->
            <div class="slider-wrapper">
                <div class="slider" id="slider">
                    <div class="slides">
                        {% for image in post.images.all %}
                            <img src="{{ image.image_file.url }}" alt="">
                        {% endfor %}
                    </div>

                    <button class="btn prev">❮</button>
                    <button class="btn next">❯</button>
                    <div class="dots"></div>
                </div>
            </div>

            <!-- Post Detail Section (structure only, content unchanged) -->
            <article class="post-detail--container" aria-labelledby="post-title">
                <div class="post-header">
                    <div class="meta">پست</div>
                    <div class="post-actions">
                        <button class="btn-action" title="اشتراک گذاری">اشتراک</button>
                        <button class="btn-action" title="ذخیره">ذخیره</button>
                    </div>
                </div>

                <div class="post-hero">
                    <h2 id="post-title" class="post-title">
                        {{ post.title }} <span class="post-author">by <a href="{% url 'blog:profile_detail' post.author.id %}">{{ post.author }}</a></span>
                    </h2>

                    <div class="post-description">{{ post.description | markdown }}</div>

                    <div class="post-published--container">
                        <p class="post-published">{{ post.publish | jformat:'%Y/%m/%d | %H:%M ' }}</p>
                    </div>
                </div>
            </article>

            <!-- Comments Section -->
            <div class="comments" aria-live="polite">
                <div class="muted">
                    {% with comments.count as cm_count %}
                        <p>{{ cm_count }} comment{{ cm_count | pluralize }}</p>
                    {% endwith %}
                </div>

                {% for comment in comments %}
                    <div class="comment">
                        <strong>{{ comment.name }}</strong>
                        <p>{{ comment.body | markdown }}</p>
                    </div>
                {% empty %}
                    <p class="muted">نظری وجود ندارد!</p>
                {% endfor %}
            </div>

            {% include 'forms/comment.html' %}
            <script src={% static 'JS/blog/detail.js' %}></script>
        </section>
     </main>
{% endblock %}

Blog/templates/blog/index.html
{% extends 'parent/base.html' %}
{% load static %}
{% load jformat %}
{% load blog_tags %}
{% block title %}Home{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/blog/index.css' %}">
{% endblock %}
{% block content %}
    <!-- Page Title -->
    <h2 class="page-title">آمار</h2>

    <!-- Totals -->
    <div class="totals-container">
        <p class="totals">تعداد پست‌ها<br>{% total_posts %}</p>
        <p class="totals">تعداد نظرات<br>{% total_comments %}</p>
    </div>

    <!-- Main Container -->
    <div class="main-cont">

        <!-- Latest Posts -->
        <div class="posts-container">
            <h2 class="page-title posts--title">جدیدترین پست‌ها</h2>
            {% latest_posts %}
        </div>

        <!-- Most Popular Posts -->
        <div class="posts-container">
            <h2 class="page-title posts--title">محبوب‌ترین پست‌ها</h2>
            {% most_popular_posts as pop_posts %}
            {% for post in pop_posts %}
                <div class="posts-cont">
                    <div class="post-image--cont">
                        <img class="post-image" src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
                    </div>
                    <div class="post-data">
                        <div class="profile-info--cont">
                            <img class="profile-image" src="{{ post.author.account.photo.url }}" alt="{{ post.author }}">
                            <a class="username-link" href="{% url 'blog:profile_detail' post.author.id %}">{{ post.author }}</a>
                        </div>
                        <div class="post-info">
                            <h3><a class="title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                            <div class="post-desc">{{ post.description | markdown | safe | truncatewords:25 }}</div>
                            <p class="post-time">{{ post.publish | jformat:'%Y/%m/%d | %H:%M ' }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

    <!-- Longest Post -->
    <h2>طولانی‌ترین پست</h2>
    {% max_reading_time as mart %}
    {% for post in mart %}
        <p style="text-align: center;">
            <a href="{{ post.get_absolute_url }}">{{ post.title }} : با زمان مطالعه {{ post.max_time }}</a>
        </p>
    {% endfor %}

    <!-- Shortest Post -->
    <h2>کوتاه‌ترین پست</h2>
    {% min_reading_time as mirt %}
    {% for post in mirt %}
        <p style="text-align: center;">
            <a href="{{ post.get_absolute_url }}">{{ post.title }} : با زمان مطالعه {{ post.min_time }}</a>
        </p>
    {% endfor %}
{% endblock %}

Blog/templates/blog/list.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}
    post list
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'CSS/blog/list.css' %}">
{% endblock %}
{% block content %}
    <!-- Category Links -->
    <div class="categories">
        <a href="{% url 'blog:post_list_category' 'تکنولوژِی' %}">تکنولوژِی</a>
        <a href="{% url 'blog:post_list_category' 'بلاکچین' %}">بلاکچین</a>
    </div>

    <!-- Main Title -->
    {% if category %}
        <h1 class="main-title">لیست پست های {{ category }}</h1>
    {% else %}
        <h1 class="main-title">لیست پست ها</h1>
    {% endif %} 

    <!-- Post List -->
    <ol class="ol" style="--length: {{ posts|length }}" role="list">
        {% for post in posts %}
            <li class="li" style="--i: {{ forloop.counter }}">
                <!-- Post Image -->
                {% if post.images.first %}
                    <img src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
                {% endif %}

                <!-- Post Title -->
                <h3 class="h3">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h3>

                <!-- Post Description -->
                <p>{{ post.description | truncatewords:5 }}</p>
            </li>
        {% endfor %}
    </ol>

    <!-- Pagination -->
    {% include 'partials/pagination.html' with page=posts %}
{% endblock %}

Blog/templates/blog/profile.html
{% extends 'parent/base.html' %}
{% load static %}
{% load blog_tags %}
{% load jformat %}
{% block title %}profile{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'CSS/blog/profile.css' %}">
{% endblock %}
{% block content %}

    <div class="profile-dashboard">
        <div class="user-menu">
            <div class="menu-header">
                <img src="{{ user.account.photo.url }}" alt="profile" class="menu-avatar">
                <span class="menu-username">{{ user.username }}</span>
                <button class="menu-toggle">☰</button>
            </div>

            <ul class="menu-options">
                <li><a href="{% url 'blog:edit_account' %}">✏️ ویرایش اطلاعات حساب</a></li>
                <li><a href="{% url 'blog:create_post' %}">➕ افزودن پست جدید</a></li>
                <li><a href="{% url 'blog:password_change' %}">🔑 تغییر رمز عبور</a></li>
                <li>
                    <form method="post" action="{% url 'blog:logout' %}">
                        {% csrf_token %}
                        <button class="logout" type="submit">🚪 خروج از حساب</button>
                    </form>
                </li>
            </ul>
        </div>

        <div class="table-section">
            <h2 class="posts-title">پست‌های شما</h2>
            <table class="table">
                <tr class="tr">
                    <th class="row">ردیف</th>
                    <th>پست</th>
                    <th>ویرایش</th>
                    <th>حذف</th>
                </tr>
                {% for post in posts %}
                    <tr class="tr">
                        <td class="row">{{ forloop.counter }}</td>
                        <td><a class="title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
                        <td>
                            <a href="{% url 'blog:edit_post' post.id %}">
                                <img class="icon edit" src="{% static 'icons/edit.svg' %}" alt="ویرایش">
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'blog:delete_post' post.id %}">
                                <img class="icon delete" src="{% static 'icons/delete.svg' %}" alt="حذف">
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <script>
        const toggle = document.querySelector('.menu-toggle');
        const menu = document.querySelector('.menu-options');
        toggle.addEventListener('click', () => {
            menu.classList.toggle('open');
        });
    </script>

{% endblock %}

Blog/templates/blog/profile_detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% load jformat %}
{% load blog_tags %}
{% block title %}personal info{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'CSS/blog/profile_details.css' %}">
{% endblock %}
{% block content %}

<div class="profile-page container">

    <!-- ===== بخش اطلاعات کاربر ===== -->
    <section class="profile-info--section card">
        <div class="profile-header">
            <img class="profile-picture" src="{{ account.photo.url }}" alt="{{ user.username }}">
            <h2 class="username-text">{{ user.username }}</h2>
        </div>

        <div class="important-info">
            <h3 class="name-text">{{ user.first_name }} {{ user.last_name }}</h3>
            <p class="job-text">فعال در حوزه {{ account.job }}ی</p>
        </div>

        <hr class="divider">

        <div class="bio-container">
            <p class="bio-text">{{ account.bio }}</p>
            <p class="birth-text">{{ account.date_of_birth }} متولد شده</p>
        </div>
    </section>

    <!-- ===== بخش پست‌های کاربر ===== -->
    <section class="user-posts--section">
        <h2 class="totals">پست‌های {{ user.username }}</h2>

        <div class="posts-grid">
            {% for post in posts %}
                <article class="post-card card">
                    <div class="post-image--cont">
                        <img class="post-image" src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
                    </div>
                    <div class="post-data">
                        <div class="profile-info--cont">
                            <img class="profile-image" src="{{ post.author.account.photo.url }}" alt="{{ post.author }}">
                            <a class="username-link" href="{% url 'blog:profile_detail' post.author.id %}">{{ post.author }}</a>
                        </div>
                        <div class="post-info">
                            <h3 class="title-cont">
                                <a class="title" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h3>
                            <p class="post-desc">{{ post.description | markdown | safe | truncatewords:25 }}</p>
                            <p class="post-time">{{ post.publish | jformat:'%Y/%m/%d | %H:%M ' }}</p>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>

</div>

{% endblock %}

Blog/templates/blog/search.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}search list{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'CSS/blog/list.css' %}">
{% endblock %}
{% block content %}
    {% if query %}
        <h2>
        <span>نتیجه جستجو برای</span>
        <span>"{{ query }}"</span>
        <span>:در پست ها</span>
        <span>{{ results.count }}</span>
        </h2>
    {% endif %}
    <br>
     <ol class="ol" style="--length: {{ results|length }}" role="list">
        {% for post in results %}
            <li class="li" style="--i: {{ forloop.counter }}">
                <h3 class="h3">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h3>
                <p>{{ post.description | truncatewords:10 }}</p>
            </li>
        {% empty %}
            <h3>!متاسفانه هیچ نتیجه ای پیدا نشد</h3>
        {% endfor %}
    </ol>
    
{% endblock %}